//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorizationRequest
    {
        public int Id { get; set; }
        public Nullable<int> providerid { get; set; }
        public string providerName { get; set; }
        public string policynumber { get; set; }
        public string fullname { get; set; }
        public string company { get; set; }
        public string diagnosis { get; set; }
        public string reasonforcode { get; set; }
        public Nullable<bool> isnew { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SiteId { get; set; }
    }
}
