//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchRunResult
    {
        public int Id { get; set; }
        public Nullable<int> ExecutionOrder { get; set; }
        public Nullable<decimal> MillisecondsTaken { get; set; }
        public string Status { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> BatchRunId { get; set; }
        public Nullable<int> BatchJobId { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        public virtual BatchJob BatchJob { get; set; }
        public virtual BatchRun BatchRun { get; set; }
    }
}
