//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Claim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Claim()
        {
            this.ClaimDrugs = new HashSet<ClaimDrug>();
            this.ClaimServices = new HashSet<ClaimService>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Provider Id")]
        public Nullable<int> ProviderId { get; set; }
        [Display(Name = "Enrollee Id")]
        public Nullable<int> Enrolleeid { get; set; }
        [Display(Name = "Full Name")]
        public string enrolleeFullname { get; set; }
        [Display(Name = "Sex ")]
        public string enrolleeGender { get; set; }
        [Display(Name = "Company")]
        public string enrolleeCompanyName { get; set; }
        [Display(Name = "Company Id")]
        public Nullable<int> enrolleeCompanyId { get; set; }
        [Display(Name = "Policy Number")]
        public string enrolleePolicyNumber { get; set; }
        [Display(Name = "Enrollee Plan")]
        public string EnrolleePlan { get; set; }
        [Display(Name = "Claim No")]
        public string ClaimsSerialNo { get; set; }
        [Display(Name = "EVS Code")]
        public string EVSCode { get; set; }
        [Display(Name = "Doctor's Name")]
        public string DoctorsName { get; set; }
        [Display(Name = "Doctor's Id")]
        public string DoctorsId { get; set; }
        [Display(Name = "Doctor's Specialty")]
        public string AreaOfSpecialty { get; set; }
        [Display(Name = "Doctor Signature")]
        public string Signature { get; set; }
        [Display(Name = "Doctor Signed?")]
        public Nullable<bool> DoctorSigned { get; set; }
        [Display(Name = "Signature Date")]
        public Nullable<System.DateTime> DoctorSignecDate { get; set; }
        [Display(Name = "Specialist")]
        public string specialistName { get; set; }
        [Display(Name = "Area of Specialization")]
        public string AreaOfSpecialtyforspecialist { get; set; }
        [Display(Name = "Phone Number")]
        public string specialistphonenumber { get; set; }
        [Display(Name = "Specialist Signed?")]
        public Nullable<bool> specialistSigned { get; set; }
        [Display(Name = "Signature Date")]
        public Nullable<System.DateTime> specialistSignecDate { get; set; }
        [Display(Name = "Service Date")]
        public Nullable<System.DateTime> ServiceDate { get; set; }
        [Display(Name = "Admission Date")]
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        [Display(Name = "Discharge Date")]
        public Nullable<System.DateTime> DischargeDate { get; set; }
        [Display(Name = "Duration Of Treatment")]
        public string Durationoftreatment { get; set; }
        [Display(Name = "Diagnosis")]
        public string Diagnosis { get; set; }
        [Display(Name = "Treatment Given")]
        public string TreatmentGiven { get; set; }
        [Display(Name = "Treatment Code")]
        public string TreatmentCode { get; set; }
        [Display(Name = "Referal Code")]
        public string referalCode { get; set; }
        [Display(Name = "Enrollee Sign")]
        public Nullable<bool> enrolleeSigned { get; set; }
        [Display(Name = "Signature Date")]
        public Nullable<System.DateTime> EnrolleeSignDate { get; set; }
        [Display(Name = "All Prescribed Drugs")]
        public Nullable<bool> AllprescibedDrugs { get; set; }
        [Display(Name = "Laboratory Investigation")]
        public Nullable<bool> LaboratoryInvestigation { get; set; }
        public Nullable<bool> Admission { get; set; }
        public Nullable<bool> Feeding { get; set; }
        public string Note { get; set; }
        public string Tag { get; set; }
        [Display(Name = "Captured By")]
        public Nullable<int> capturedBy { get; set; }
        [Display(Name = "Capturer")]
        public string capturedName { get; set; }
        [Display(Name = "Vetted By")]
        public Nullable<int> vettedBy { get; set; }
        [Display(Name = "Revetted By")]
        public Nullable<int> RevettedBy { get; set; }
        [Display(Name = "Date Vetted")]
        public Nullable<System.DateTime> VettedDate { get; set; }
        [Display(Name = "Date Revetted")]
        public Nullable<System.DateTime> ReVettedDate { get; set; }
        [Display(Name = "Status")]
        public string status { get; set; }
        public System.Guid Guid { get; set; }
        [Display(Name = "Captured On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Edited On")]
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        [Display(Name = "Is Deleted?")]
        public Nullable<bool> IsDeleted { get; set; }
        [Display(Name = "Claim Batch Id")]
        public Nullable<int> ClaimBatchId { get; set; }
        public Nullable<int> SiteId { get; set; }
        [Display(Name = "Enrollee Age")]
        public string enrolleeage { get; set; }
        [Display(Name = "Client Side Id")]
        public string ClientsideID { get; set; }
        
        public string diagnosticsIDString { get; set; }
        [Display(Name = "Submitted By")]
        public Nullable<bool> SubmitByProvider { get; set; }
        public string ipaddressofprovider { get; set; }
        [Display(Name = "My User Id")]
        public Nullable<int> MyUserId { get; set; }
        [Display(Name = "Vetter")]
        public string vettedName { get; set; }
       
        public List<Provider> Providers { get; set; }
        
        public List<User> Users { get; set; }
        public List<Company> Companies { get; set; }
        public List<Enrollee> Enrollees { get; set; }
        public List<PaymentBatch> PaymentBatches { get; set; }
        public List<ClaimDrug> ClaimDrug { get; set; }
        public List<ClaimService> ClaimService { get; set; }
        public List<ClaimBatch> ClaimBatches { get; set; }

    
        public virtual ClaimBatch ClaimBatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimDrug> ClaimDrugs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimService> ClaimServices { get; set; }
    }
}
