//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ClaimDrug
    {
        public int Id { get; set; }
        [Display(Name = "Drug Name")]
        public string DrugName { get; set; }
        [Display(Name = "Drug Description")]
        public string DrugDescription { get; set; }
        [Display(Name = "Quantity")]
        public string Quantity { get; set; }
        [Display(Name = "Rate")]
        public string rate { get; set; }
        [Display(Name = "Initial Amount")]
        public Nullable<decimal> InitialAmount { get; set; }
        [Display(Name = "Cost Of Drug")]
        public Nullable<decimal> costofdrug { get; set; }
        public Nullable<bool> flagred { get; set; }
        [Display(Name = "Drug Id")]
        public Nullable<int> DrugId { get; set; }
        [Display(Name = "Amount Vetted")]
        public Nullable<decimal> VettedAmount { get; set; }
        [Display(Name = "Vetting Comment")]
        public string VettingComment { get; set; }
        [Display(Name = "Status")]
        public string status { get; set; }
        public System.Guid Guid { get; set; }
        [Display(Name = "Vetted On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Updated On")]
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        [Display(Name = "Is Deleted")]
        public Nullable<bool> IsDeleted { get; set; }
        [Display(Name = "Claim Id")]
        public Nullable<int> ClaimId { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        public virtual Claim Claim { get; set; }
    }
}
