//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ClaimBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClaimBatch()
        {
            this.Claims = new HashSet<Claim>();
            this.IncomingClaims = new HashSet<IncomingClaim>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Provider Id")]
        public Nullable<int> ProviderId { get; set; }
        [Display(Name = "Month")]
        public Nullable<int> month { get; set; }
        [Display(Name = "Year")]
        public Nullable<int> year { get; set; }
        public string Batch { get; set; }
        [Display(Name = "Status")]
        public string status { get; set; }
        [Display(Name = "Submitted Vet By")]
        public Nullable<int> submitedVetbyUser { get; set; }
        [Display(Name = "Submitted Review")]
        public Nullable<int> submitedReviewbyUser { get; set; }
        [Display(Name = "Date Submitted for Review")]
        public Nullable<System.DateTime> SubmitedForReviewDate { get; set; }
        [Display(Name = "Review Date")]
        public Nullable<System.DateTime> reviewDate { get; set; }
        [Display(Name = "Reviewed By")]
        public Nullable<int> reviewedBy { get; set; }
        [Display(Name = "Vetted On")]
        public Nullable<System.DateTime> VetDate { get; set; }
        [Display(Name = "Payment Submission Date")]
        public Nullable<System.DateTime> SubmitedForPaymentDate { get; set; }
        [Display(Name = "Submitted By")]
        public Nullable<int> submitedPaymentbyUser { get; set; }
        [Display(Name = "Authorization Status")]
        public string AuthorizationStatus { get; set; }
        [Display(Name = "Authorization Note")]
        public string AuthorizationNote { get; set; }
        [Display(Name = "Disapprove Note")]
        public string DisapprovalNote { get; set; }
        [Display(Name = "Authorized By")]
        public Nullable<int> AuthorizedBy { get; set; }
        [Display(Name = "Disapproved By")]
        public Nullable<int> DisapprovedBy { get; set; }
        [Display(Name = "Authorization Date")]
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        [Display(Name = "Disapproval Date")]
        public Nullable<System.DateTime> DisapprovalDate { get; set; }
        [Display(Name = "Deletion Note")]
        public string DeletionNote { get; set; }
        public System.Guid Guid { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Edited On")]
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        [Display(Name = "Is Deleted")]
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SiteId { get; set; }
        [Display(Name = "Payment Batch Id")]
        public Nullable<int> paymentbatchId { get; set; }
        [Display(Name = "Amount Paid")]
        public Nullable<decimal> AmountPaid { get; set; }
        [Display(Name = "Payment Method")]
        public string paymentmethod { get; set; }
        [Display(Name = "Payment Reference")]
        public string paymentref { get; set; }
        [Display(Name = "Cheque Number")]
        public string chequeno { get; set; }
        [Display(Name = "Bank Name")]
        public string sourceBankName { get; set; }
        [Display(Name = "Bank Account Number")]
        public string sourceBankAccountNo { get; set; }
        [Display(Name = "Destination Bank Name")]
        public string DestBankName { get; set; }
        [Display(Name = "Destination Bank Account No")]
        public string DestBankAccountNo { get; set; }
        [Display(Name = "Remark")]
        public string remark { get; set; }
        [Display(Name = "Payment Date")]
        public Nullable<System.DateTime> paymentdate { get; set; }
        [Display(Name = "Paid By")]
        public string paidby { get; set; }
        [Display(Name = "Mark Paid By")]
        public Nullable<int> markpaidby { get; set; }
        [Display(Name = "Provider Name")]
        public string ProviderName { get; set; }
        [Display(Name = "Claim Count")]
        public Nullable<int> claimscountfromclient { get; set; }
        [Display(Name = "Payment Method")]
        public string paymentmethodstring { get; set; }
        [Display(Name = "Payment Advice Sent")]
        public Nullable<bool> paymentadvicesent { get; set; }
        [Display(Name = "Date Payment Advice Sent")]
        public Nullable<System.DateTime> datepaymentadvicesent { get; set; }
        [Display(Name = "Is Remote")]
        public Nullable<bool> isremote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual PaymentBatch PaymentBatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomingClaim> IncomingClaims { get; set; }
    }
}
