//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimAnalysisOffline
    {
        public int Id { get; set; }
        public string PROVIDER { get; set; }
        public string LOCATION { get; set; }
        public string CLIENTNAME { get; set; }
        public string COMPANY { get; set; }
        public string POLICYNUMBER { get; set; }
        public string HEALTHPLAN { get; set; }
        public Nullable<System.DateTime> ENCOUNTERDATE { get; set; }
        public Nullable<System.DateTime> DATERECEIVED { get; set; }
        public string DIAGNOSIS { get; set; }
        public string CLASS { get; set; }
        public Nullable<decimal> AMOUNTSUBMITTED { get; set; }
        public Nullable<decimal> AMOUNTPROCESSED { get; set; }
        public string TREATMENT { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> PROVIDERID { get; set; }
        public Nullable<int> SerialNo { get; set; }
    }
}
