//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.CompanyBranches = new HashSet<CompanyBranch>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<long> Stateid { get; set; }
        public Nullable<long> Parentid { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string PhoneNumber { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> Logoid { get; set; }
        public Nullable<int> SubscriptionStatus { get; set; }
        public string Plans { get; set; }
        public Nullable<int> AuthorizationStatus { get; set; }
        public string AuthorizationNote { get; set; }
        public string DisapprovalNote { get; set; }
        public Nullable<int> AuthorizedBy { get; set; }
        public Nullable<int> DisapprovedBy { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public Nullable<System.DateTime> DisapprovalDate { get; set; }
        public string DeletionNote { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SubsidiaryId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> CompanyListPageId { get; set; }
        public Nullable<bool> Status { get; set; }
        public string LogoLink { get; set; }
        public string regCode { get; set; }
        public Nullable<int> RegAgeLimit { get; set; }
        public Nullable<bool> WeboperationMode { get; set; }
        public Nullable<bool> isRenewal { get; set; }
    
        public virtual Document Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyBranch> CompanyBranches { get; set; }
    }
}
