//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyPlan
    {
        public int Id { get; set; }
        public Nullable<int> Companyid { get; set; }
        public Nullable<int> Planid { get; set; }
        public string Planfriendlyname { get; set; }
        public Nullable<decimal> AnnualPremium { get; set; }
        public Nullable<decimal> Discountlump { get; set; }
        public Nullable<decimal> Discountperenrollee { get; set; }
        public Nullable<int> Createdby { get; set; }
        public string Description { get; set; }
        public Nullable<int> AuthorizationStatus { get; set; }
        public string AuthorizationNote { get; set; }
        public Nullable<bool> AllowChildEnrollee { get; set; }
        public string DisapprovalNote { get; set; }
        public Nullable<int> AuthorizedBy { get; set; }
        public Nullable<int> DisapprovedBy { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public Nullable<System.DateTime> DisapprovalDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> MaxNoOfDependant { get; set; }
        public string ProviderConsession { get; set; }
    }
}
