//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectCareSponsor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConnectCareSponsor()
        {
            this.ConnectCareBeneficiaries = new HashSet<ConnectCareBeneficiary>();
        }
    
        public int Id { get; set; }
        public string fullname { get; set; }
        public string gender { get; set; }
        public string occupation { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phonenumber { get; set; }
        public Nullable<bool> emailsent { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string SubscriptionType { get; set; }
        public string sponsorID { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string secondarysponsor { get; set; }
        public string zipcode { get; set; }
        public Nullable<bool> Addon { get; set; }
        public Nullable<System.DateTime> SponsorStartDate { get; set; }
        public Nullable<System.DateTime> PolicyStartDate { get; set; }
        public Nullable<System.DateTime> PolicyEndDate { get; set; }
        public Nullable<int> PolicynotificationConfig { get; set; }
        public Nullable<int> instalment { get; set; }
        public string policynumner { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> Administeredby { get; set; }
        public Nullable<System.DateTime> AdministrationDate { get; set; }
        public Nullable<int> EnrolleeprofileId { get; set; }
        public string sponsorSTRID { get; set; }
        public string policynumber { get; set; }
        public Nullable<bool> pushedtoMatontine { get; set; }
        public Nullable<System.DateTime> pushedDate { get; set; }
        public Nullable<int> ManageSponsorPageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectCareBeneficiary> ConnectCareBeneficiaries { get; set; }
        public virtual Document Document { get; set; }
    }
}
