//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectCareBeneficiary
    {
        public int Id { get; set; }
        public string fullname { get; set; }
        public string gender { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string phonenumber { get; set; }
        public string relationship { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> sponsorid { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string BeneficiaryCat { get; set; }
        public byte[] Passport { get; set; }
        public string BeneficiaryID { get; set; }
        public string firstname { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string lastname { get; set; }
        public string LGA { get; set; }
        public string GuardianPhonenumber { get; set; }
        public string GuardianEmail { get; set; }
        public string SuggestedProvider { get; set; }
        public string suggestedPlan { get; set; }
        public string PolicyNumber { get; set; }
        public Nullable<bool> VerificationStatus { get; set; }
        public Nullable<bool> active { get; set; }
        public string Status { get; set; }
        public string Category { get; set; }
        public Nullable<bool> addon { get; set; }
        public Nullable<int> Administeredby { get; set; }
        public Nullable<System.DateTime> AdministrationDate { get; set; }
        public Nullable<int> ConnectCareSponsorId { get; set; }
        public string sponsoridstring { get; set; }
    
        public virtual ConnectCareSponsor ConnectCareSponsor { get; set; }
    }
}
