//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_A0009D_NovoHubEntities : DbContext
    {
        public DB_A0009D_NovoHubEntities()
            : base("name=DB_A0009D_NovoHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_TransactionIndex_7ad3eb30_9dbe_4fdb_bed2_b17433c5890f> C_TransactionIndex_7ad3eb30_9dbe_4fdb_bed2_b17433c5890f { get; set; }
        public virtual DbSet<ACLRole> ACLRoles { get; set; }
        public virtual DbSet<AdminAllowedRole> AdminAllowedRoles { get; set; }
        public virtual DbSet<AdminDisallowedRole> AdminDisallowedRoles { get; set; }
        public virtual DbSet<AuthorizationCode> AuthorizationCodes { get; set; }
        public virtual DbSet<AuthorizationRequest> AuthorizationRequests { get; set; }
        public virtual DbSet<AutomaticExpungeStaff> AutomaticExpungeStaffs { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<BatchJob> BatchJobs { get; set; }
        public virtual DbSet<BatchRun> BatchRuns { get; set; }
        public virtual DbSet<BatchRunResult> BatchRunResults { get; set; }
        public virtual DbSet<Benefit> Benefits { get; set; }
        public virtual DbSet<BenefitsCategory> BenefitsCategories { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<ClaimAnalysisOffline> ClaimAnalysisOfflines { get; set; }
        public virtual DbSet<ClaimBatch> ClaimBatches { get; set; }
        public virtual DbSet<ClaimDrug> ClaimDrugs { get; set; }
        public virtual DbSet<ClaimHistory> ClaimHistories { get; set; }
        public virtual DbSet<ClaimService> ClaimServices { get; set; }
        public virtual DbSet<ClaimUpload> ClaimUploads { get; set; }
        public virtual DbSet<ClaimUpload2> ClaimUpload2 { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyAssignee> CompanyAssignees { get; set; }
        public virtual DbSet<CompanyBenefit> CompanyBenefits { get; set; }
        public virtual DbSet<CompanyBranch> CompanyBranches { get; set; }
        public virtual DbSet<CompanyPlan> CompanyPlans { get; set; }
        public virtual DbSet<CompanySubsidiary> CompanySubsidiaries { get; set; }
        public virtual DbSet<ConnectCareBeneficiary> ConnectCareBeneficiaries { get; set; }
        public virtual DbSet<ConnectcarePaymentDetail> ConnectcarePaymentDetails { get; set; }
        public virtual DbSet<ConnectCareSponsor> ConnectCareSponsors { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DeletedEnrollee> DeletedEnrollees { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentTag> DocumentTags { get; set; }
        public virtual DbSet<DocumentVersion> DocumentVersions { get; set; }
        public virtual DbSet<DownloadFile> DownloadFiles { get; set; }
        public virtual DbSet<DrugTariff> DrugTariffs { get; set; }
        public virtual DbSet<EmailDEST> EmailDESTs { get; set; }
        public virtual DbSet<Enrollee> Enrollees { get; set; }
        public virtual DbSet<EnrolleePassport> EnrolleePassports { get; set; }
        public virtual DbSet<EnrolleePreexistingMedicalHistory> EnrolleePreexistingMedicalHistories { get; set; }
        public virtual DbSet<EnrolleeVerificationCode> EnrolleeVerificationCodes { get; set; }
        public virtual DbSet<ExpungedEnrollee> ExpungedEnrollees { get; set; }
        public virtual DbSet<FacilitiesAllowed> FacilitiesAlloweds { get; set; }
        public virtual DbSet<FacilitiesAllowedssss> FacilitiesAllowedsssses { get; set; }
        public virtual DbSet<Fak> Faks { get; set; }
        public virtual DbSet<Faq> Faqs { get; set; }
        public virtual DbSet<Faq1> Faqs1 { get; set; }
        public virtual DbSet<FormListOption> FormListOptions { get; set; }
        public virtual DbSet<FormPosting> FormPostings { get; set; }
        public virtual DbSet<FormProperty> FormProperties { get; set; }
        public virtual DbSet<FormValue> FormValues { get; set; }
        public virtual DbSet<FrontEndAllowedRole> FrontEndAllowedRoles { get; set; }
        public virtual DbSet<FrontEndDisallowedRole> FrontEndDisallowedRoles { get; set; }
        public virtual DbSet<FrontEndWebpageRole> FrontEndWebpageRoles { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<HiddenWidget> HiddenWidgets { get; set; }
        public virtual DbSet<IncomingClaim> IncomingClaims { get; set; }
        public virtual DbSet<Issue> Issues { get; set; }
        public virtual DbSet<LayoutArea> LayoutAreas { get; set; }
        public virtual DbSet<Lga> Lgas { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<LuceneFieldBoost> LuceneFieldBoosts { get; set; }
        public virtual DbSet<MaritalStatu> MaritalStatus { get; set; }
        public virtual DbSet<MediaFile> MediaFiles { get; set; }
        public virtual DbSet<MessageTemplate> MessageTemplates { get; set; }
        public virtual DbSet<MobileSignup> MobileSignups { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationTable> NotificationTables { get; set; }
        public virtual DbSet<NovoStaff> NovoStaffs { get; set; }
        public virtual DbSet<NovoStaffResponsibility> NovoStaffResponsibilities { get; set; }
        public virtual DbSet<OfflineMessage> OfflineMessages { get; set; }
        public virtual DbSet<PageTemplate> PageTemplates { get; set; }
        public virtual DbSet<PageWidgetSort> PageWidgetSorts { get; set; }
        public virtual DbSet<PaymentBatch> PaymentBatches { get; set; }
        public virtual DbSet<PendingDependant> PendingDependants { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<PlanDefaultBenefit> PlanDefaultBenefits { get; set; }
        public virtual DbSet<PreExistingMedicalHistoryList> PreExistingMedicalHistoryLists { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<ProviderAccount> ProviderAccounts { get; set; }
        public virtual DbSet<ProviderAssignee> ProviderAssignees { get; set; }
        public virtual DbSet<ProviderClaimBK> ProviderClaimBKs { get; set; }
        public virtual DbSet<ProviderLogin> ProviderLogins { get; set; }
        public virtual DbSet<ProviderRating> ProviderRatings { get; set; }
        public virtual DbSet<ProviderService> ProviderServices { get; set; }
        public virtual DbSet<QueuedMessage> QueuedMessages { get; set; }
        public virtual DbSet<QueuedMessageAttachment> QueuedMessageAttachments { get; set; }
        public virtual DbSet<QueuedTask> QueuedTasks { get; set; }
        public virtual DbSet<RedirectedDomain> RedirectedDomains { get; set; }
        public virtual DbSet<ResizedImage> ResizedImages { get; set; }
        public virtual DbSet<ScheduledTask> ScheduledTasks { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceTariff> ServiceTariffs { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<ShortCodeMsg> ShortCodeMsgs { get; set; }
        public virtual DbSet<ShownWidget> ShownWidgets { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<Sm> Sms { get; set; }
        public virtual DbSet<SmsConfig> SmsConfigs { get; set; }
        public virtual DbSet<SponsorShipType> SponsorShipTypes { get; set; }
        public virtual DbSet<Staff_Old_20180628> Staff_Old_20180628 { get; set; }
        public virtual DbSet<StaffUploadJob> StaffUploadJobs { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<StringResource> StringResources { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<Symposium> Symposiums { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Tariff> Tariffs { get; set; }
        public virtual DbSet<TariffCategory> TariffCategories { get; set; }
        public virtual DbSet<TaskShit> TaskShits { get; set; }
        public virtual DbSet<TempEnrollee> TempEnrollees { get; set; }
        public virtual DbSet<TerminatedSubscription> TerminatedSubscriptions { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<testable> testables { get; set; }
        public virtual DbSet<UrlHistory> UrlHistories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<UserNotification> UserNotifications { get; set; }
        public virtual DbSet<UserProfileData> UserProfileDatas { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<UsersToRole> UsersToRoles { get; set; }
        public virtual DbSet<VettingProtocol> VettingProtocols { get; set; }
        public virtual DbSet<Widget> Widgets { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
        public virtual DbSet<Query> Queries { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Staff_Old_20180702> Staff_Old_20180702 { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        [DbFunction("DB_A0009D_NovoHubEntities", "SplitString")]
        public virtual IQueryable<SplitString_Result> SplitString(string str, string separator)
        {
            var strParameter = str != null ?
                new ObjectParameter("str", str) :
                new ObjectParameter("str", typeof(string));
    
            var separatorParameter = separator != null ?
                new ObjectParameter("separator", separator) :
                new ObjectParameter("separator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[DB_A0009D_NovoHubEntities].[SplitString](@str, @separator)", strParameter, separatorParameter);
        }
    
        public virtual int CheckActiveSubscription()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CheckActiveSubscription");
        }
    
        public virtual int CheckNewSubscription()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CheckNewSubscription");
        }
    
        public virtual int DoExpirationCheck()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DoExpirationCheck");
        }
    
        public virtual ObjectResult<STP_CLAIM_BATCH_DRUGS_Result> STP_CLAIM_BATCH_DRUGS(string providerId, string claimBatchId)
        {
            var providerIdParameter = providerId != null ?
                new ObjectParameter("ProviderId", providerId) :
                new ObjectParameter("ProviderId", typeof(string));
    
            var claimBatchIdParameter = claimBatchId != null ?
                new ObjectParameter("ClaimBatchId", claimBatchId) :
                new ObjectParameter("ClaimBatchId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_CLAIM_BATCH_DRUGS_Result>("STP_CLAIM_BATCH_DRUGS", providerIdParameter, claimBatchIdParameter);
        }
    
        public virtual ObjectResult<STP_CLAIM_BATCH_SERVICE_Result> STP_CLAIM_BATCH_SERVICE(string providerId, string claimBatchId)
        {
            var providerIdParameter = providerId != null ?
                new ObjectParameter("ProviderId", providerId) :
                new ObjectParameter("ProviderId", typeof(string));
    
            var claimBatchIdParameter = claimBatchId != null ?
                new ObjectParameter("ClaimBatchId", claimBatchId) :
                new ObjectParameter("ClaimBatchId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_CLAIM_BATCH_SERVICE_Result>("STP_CLAIM_BATCH_SERVICE", providerIdParameter, claimBatchIdParameter);
        }
    }
}
