//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Companies = new HashSet<Company>();
            this.ConnectCareSponsors = new HashSet<ConnectCareSponsor>();
            this.DocumentVersions = new HashSet<DocumentVersion>();
            this.DownloadFiles = new HashSet<DownloadFile>();
            this.FacilitiesAlloweds = new HashSet<FacilitiesAllowed>();
            this.Faks = new HashSet<Fak>();
            this.Faqs = new HashSet<Faq>();
            this.FormPostings = new HashSet<FormPosting>();
            this.FormProperties = new HashSet<FormProperty>();
            this.LayoutAreas = new HashSet<LayoutArea>();
            this.Lgas = new HashSet<Lga>();
            this.Lgas1 = new HashSet<Lga>();
            this.Lgas2 = new HashSet<Lga>();
            this.Lgas3 = new HashSet<Lga>();
            this.Lgas4 = new HashSet<Lga>();
            this.Lgas5 = new HashSet<Lga>();
            this.MediaFiles = new HashSet<MediaFile>();
            this.PageTemplates = new HashSet<PageTemplate>();
            this.PageWidgetSorts = new HashSet<PageWidgetSort>();
            this.Plans = new HashSet<Plan>();
            this.Providers = new HashSet<Provider>();
            this.Providers1 = new HashSet<Provider>();
            this.Providers2 = new HashSet<Provider>();
            this.Providers3 = new HashSet<Provider>();
            this.Providers4 = new HashSet<Provider>();
            this.Providers5 = new HashSet<Provider>();
            this.Services = new HashSet<Service>();
            this.States = new HashSet<State>();
            this.States1 = new HashSet<State>();
            this.States2 = new HashSet<State>();
            this.States3 = new HashSet<State>();
            this.States4 = new HashSet<State>();
            this.States5 = new HashSet<State>();
            this.Tariffs = new HashSet<Tariff>();
            this.UrlHistories = new HashSet<UrlHistory>();
            this.Widgets = new HashSet<Widget>();
            this.ShownWidgets = new HashSet<ShownWidget>();
            this.HiddenWidgets = new HashSet<HiddenWidget>();
            this.DocumentTags = new HashSet<DocumentTag>();
            this.ShownWidgets1 = new HashSet<ShownWidget>();
            this.DocumentTags1 = new HashSet<DocumentTag>();
            this.HiddenWidgets1 = new HashSet<HiddenWidget>();
            this.FrontEndWebpageRoles = new HashSet<FrontEndWebpageRole>();
            this.FrontEndWebpageRoles1 = new HashSet<FrontEndWebpageRole>();
        }
    
        public int Id { get; set; }
        public string DocumentType { get; set; }
        public string Name { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> HideInAdminNav { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string UrlSegment { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<bool> IsGallery { get; set; }
        public string SEOTargetPhrase { get; set; }
        public Nullable<bool> RevealInNavigation { get; set; }
        public Nullable<bool> RequiresSSL { get; set; }
        public Nullable<System.DateTime> PublishOn { get; set; }
        public Nullable<bool> BlockAnonymousAccess { get; set; }
        public string FormRedirectUrl { get; set; }
        public string FormEmailTitle { get; set; }
        public Nullable<bool> InheritFrontEndRolesFromParent { get; set; }
        public Nullable<bool> ShowOnlyIfPermitted { get; set; }
        public string FaIcon { get; set; }
        public string BodyContent { get; set; }
        public string MetaKeywords { get; set; }
        public bool Published { get; set; }
        public bool IncludeInSitemap { get; set; }
        public string CustomFooterScripts { get; set; }
        public string CustomHeaderScripts { get; set; }
        public string SendFormTo { get; set; }
        public string FormMessage { get; set; }
        public string FormSubmittedMessage { get; set; }
        public string FormDesign { get; set; }
        public string SubmitButtonCssClass { get; set; }
        public string SubmitButtonText { get; set; }
        public Nullable<int> PageTemplateId { get; set; }
        public string RedirectUrl { get; set; }
        public Nullable<bool> Permanent { get; set; }
        public string BenefitName { get; set; }
        public string PlanName { get; set; }
        public string ParentcompanyName { get; set; }
        public Nullable<int> Parentcompanyid { get; set; }
        public string PlanId { get; set; }
        public string Createdby { get; set; }
        public string Description { get; set; }
        public string CustomizePlanName { get; set; }
        public string Companyplanid { get; set; }
        public string CompanyName { get; set; }
        public string PlanType { get; set; }
        public string Planfriendlyname { get; set; }
        public string AnnualPremium { get; set; }
        public string Discountlump { get; set; }
        public string Discountperenrollee { get; set; }
        public Nullable<bool> AllowChildEnrollee { get; set; }
        public Nullable<int> EnrolleemodelId { get; set; }
        public string Staff { get; set; }
        public Nullable<int> ConfigId { get; set; }
        public string TarrifName { get; set; }
        public Nullable<bool> ShowEditButtonToUser { get; set; }
        public string FeatureImage { get; set; }
        public string Abstract { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PageSize { get; set; }
        public Nullable<bool> AllowPaging { get; set; }
        public string ThumbnailImage { get; set; }
        public Nullable<int> MediaGalleryId { get; set; }
        public string Verification { get; set; }
        public string ErrorMessage { get; set; }
        public string Message { get; set; }
        public string Passport { get; set; }
        public string Fullname { get; set; }
        public string PolicyNumber { get; set; }
        public string Gender { get; set; }
        public string Company { get; set; }
        public string Verificationcode { get; set; }
        public string Hospital { get; set; }
        public Nullable<int> ClaimsId { get; set; }
        public Nullable<int> ClaimId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> Companyid { get; set; }
        public Nullable<int> EnrolleeId { get; set; }
        public string ProviderId { get; set; }
        public Nullable<int> providermodelId { get; set; }
        public string shiitt { get; set; }
        public string Sponsor { get; set; }
        public Nullable<int> paymentbatchId { get; set; }
        public string urlReturn { get; set; }
        public string tony { get; set; }
        public string FacilitiesAllowedName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectCareSponsor> ConnectCareSponsors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentVersion> DocumentVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DownloadFile> DownloadFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacilitiesAllowed> FacilitiesAlloweds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fak> Faks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faq> Faqs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormPosting> FormPostings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormProperty> FormProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LayoutArea> LayoutAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lga> Lgas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lga> Lgas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lga> Lgas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lga> Lgas3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lga> Lgas4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lga> Lgas5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediaFile> MediaFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageTemplate> PageTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageWidgetSort> PageWidgetSorts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan> Plans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State> States { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State> States1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State> States2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State> States3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State> States4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State> States5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tariff> Tariffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrlHistory> UrlHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Widget> Widgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShownWidget> ShownWidgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HiddenWidget> HiddenWidgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentTag> DocumentTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShownWidget> ShownWidgets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentTag> DocumentTags1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HiddenWidget> HiddenWidgets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrontEndWebpageRole> FrontEndWebpageRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrontEndWebpageRole> FrontEndWebpageRoles1 { get; set; }
    }
}
