//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrolleeVerificationCode
    {
        public int Id { get; set; }
        public Nullable<int> EnrolleeId { get; set; }
        public string Status { get; set; }
        public string VerificationCode { get; set; }
        public Nullable<System.DateTime> EncounterDate { get; set; }
        public Nullable<System.DateTime> DateAuthenticated { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
        public Nullable<int> Channel { get; set; }
        public string RequestPhoneNumber { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> VisitPurpose { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string Note { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> AuthChannel { get; set; }
        public Nullable<bool> Pickedup { get; set; }
        public Nullable<int> PickedUpById { get; set; }
        public Nullable<bool> AttendedTo { get; set; }
        public Nullable<System.DateTime> DateAttendedTo { get; set; }
        public string ServiceAccessed { get; set; }
        public Nullable<bool> AuthorizationCodeGiven { get; set; }
        public string AuthorizationCode { get; set; }
        public Nullable<int> AuthorizedByUserId { get; set; }
        public Nullable<System.DateTime> DateAuthorized { get; set; }
        public string AgentNote { get; set; }
        public Nullable<bool> PostSMSSent { get; set; }
        public string visittype { get; set; }
    }
}
