//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollee
    {
        public int Id { get; set; }
        public Nullable<int> Parentid { get; set; }
        public Nullable<int> Parentrelationship { get; set; }
        public string Policynumber { get; set; }
        public string Title { get; set; }
        public string Surname { get; set; }
        public string Othernames { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Maritalstatus { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Residentialaddress { get; set; }
        public Nullable<int> Stateid { get; set; }
        public Nullable<int> Lgaid { get; set; }
        public string Mobilenumber { get; set; }
        public string Emailaddress { get; set; }
        public Nullable<int> Sponsorshiptype { get; set; }
        public string Sponsorshiptypeothername { get; set; }
        public string Preexistingmedicalhistory { get; set; }
        public string Sponsorshiptypenote { get; set; }
        public Nullable<int> Companyid { get; set; }
        public Nullable<int> Subscriptionplanid { get; set; }
        public Nullable<bool> Hasdependents { get; set; }
        public string Specialidcardfield1 { get; set; }
        public string Specialidcardfield2 { get; set; }
        public string Specialidcardfield3 { get; set; }
        public Nullable<int> Staffprofileid { get; set; }
        public Nullable<int> Primaryprovider { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Hasactivesubscription { get; set; }
        public Nullable<bool> Isexpundged { get; set; }
        public string ExpungeNote { get; set; }
        public Nullable<int> Expungedby { get; set; }
        public Nullable<System.DateTime> Dateexpunged { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Datereceived { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> EnrolleePassportId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<bool> IdCardPrinted { get; set; }
        public string RefPolicynumber { get; set; }
        public Nullable<bool> HasRefPolicyNumber { get; set; }
        public string Mobilenumber2 { get; set; }
        public Nullable<int> LastyearBirthdaymsgsent { get; set; }
        public Nullable<int> Bulkjobid { get; set; }
    }
}
