//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingClaim
    {
        public int Id { get; set; }
        public Nullable<int> providerid { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<System.DateTime> fullDateofbill { get; set; }
        public string deliveredby { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<int> receivedBy { get; set; }
        public Nullable<int> transferedTo { get; set; }
        public Nullable<int> transferstatus { get; set; }
        public Nullable<int> noofencounter { get; set; }
        public Nullable<decimal> totalamount { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> dateTransferAcknowledged { get; set; }
        public string Note { get; set; }
        public string CapturerList { get; set; }
        public Nullable<System.DateTime> captureStarted { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ClaimBatchId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string caption { get; set; }
        public Nullable<bool> IsRemoteSubmission { get; set; }
        public string month_string { get; set; }
    
        public virtual ClaimBatch ClaimBatch { get; set; }
    }
}
