//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MediaFile()
        {
            this.ResizedImages = new HashSet<ResizedImage>();
        }
    
        public int Id { get; set; }
        public string MediaFileType { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string FileUrl { get; set; }
        public string FileExtension { get; set; }
        public string ContentType { get; set; }
        public Nullable<long> ContentLength { get; set; }
        public string FileName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> MediaCategoryId { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        public virtual Document Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResizedImage> ResizedImages { get; set; }
    }
}
