//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NovoStaff
    {
        public int Id { get; set; }
        public string Staff_Name { get; set; }
        public string Staff_No { get; set; }
        public string Role { get; set; }
        public string Grade { get; set; }
        public string Job_Desc { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> LineManager { get; set; }
        public string Staff_Email { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SiteId { get; set; }
    }
}
