//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingDependant
    {
        public int Id { get; set; }
        public byte[] ImgRaw { get; set; }
        public string firstName { get; set; }
        public string lastname { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> sex { get; set; }
        public Nullable<int> hospital { get; set; }
        public string mobile { get; set; }
        public string preexisting { get; set; }
        public Nullable<int> relationship { get; set; }
        public string Note { get; set; }
        public string Principalpolicynum { get; set; }
        public string principalGuid { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<bool> Approved { get; set; }
    }
}
