//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider()
        {
            this.ProviderClaimBKs = new HashSet<ProviderClaimBK>();
            this.ProviderServices1 = new HashSet<ProviderService>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string SubCode { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Website { get; set; }
        public string Address { get; set; }
        public Nullable<int> Assignee { get; set; }
        public string Providergpscordinate { get; set; }
        public string Providerservices { get; set; }
        public string Providerplans { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> AuthorizationStatus { get; set; }
        public string AuthorizationNote { get; set; }
        public string DisapprovalNote { get; set; }
        public Nullable<int> AuthorizedBy { get; set; }
        public Nullable<int> DisapprovedBy { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public Nullable<System.DateTime> DisapprovalDate { get; set; }
        public Nullable<long> Parentid { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> LgaId { get; set; }
        public Nullable<int> ProvideraccountId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> ProviderListPageId { get; set; }
        public Nullable<int> ProviderApprovalPageId { get; set; }
        public string DeletionNote { get; set; }
        public Nullable<int> TariffPageId { get; set; }
        public Nullable<int> TariffContentPageId { get; set; }
        public string ProviderTariffs { get; set; }
        public string Area { get; set; }
        public Nullable<int> Provideraccount2Id { get; set; }
        public string PaymentEmail1 { get; set; }
        public string PaymentEmail2 { get; set; }
        public Nullable<int> providerloginId { get; set; }
        public string Category { get; set; }
        public Nullable<bool> isDelisted { get; set; }
        public string DelistNote { get; set; }
        public Nullable<System.DateTime> delisteddate { get; set; }
        public Nullable<int> delistedBy { get; set; }
        public Nullable<int> DelistedProviderPageId { get; set; }
        public string CompanyConsession { get; set; }
        public Nullable<int> FacilitiesListPageId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Document Document1 { get; set; }
        public virtual Document Document2 { get; set; }
        public virtual Document Document3 { get; set; }
        public virtual Document Document4 { get; set; }
        public virtual Document Document5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderClaimBK> ProviderClaimBKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderService> ProviderServices1 { get; set; }
    }
}
