//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderLogin
    {
        public int Id { get; set; }
        public string password { get; set; }
        public Nullable<bool> passwordchange { get; set; }
        public string browserid { get; set; }
        public string lastloginId { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> LastClaimSubmited { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string email { get; set; }
        public string Altemail { get; set; }
        public string Altemail2 { get; set; }
        public string Altemail3 { get; set; }
    }
}
