//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public int Id { get; set; }
        public byte[] Imgraw { get; set; }
        public byte[] S_Imgraw { get; set; }
        public byte[] child1_Imgraw { get; set; }
        public byte[] child2_Imgraw { get; set; }
        public byte[] child3_Imgraw { get; set; }
        public byte[] child4_Imgraw { get; set; }
        public string Policynumber { get; set; }
        public string RefPolicynumber { get; set; }
        public Nullable<bool> HasRefPolicyNumber { get; set; }
        public string Title { get; set; }
        public string Surname { get; set; }
        public string Othernames { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Maritalstatus { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Residentialaddress { get; set; }
        public Nullable<int> Stateoforiginid { get; set; }
        public string Lga { get; set; }
        public Nullable<int> Stateofresidence { get; set; }
        public string Mobilenumber { get; set; }
        public string Mobilenumber2 { get; set; }
        public string Emailaddress { get; set; }
        public Nullable<int> Sponsorshiptype { get; set; }
        public string Sponsorshiptypeothername { get; set; }
        public string Preexistingmedicalhistory { get; set; }
        public string Sponsorshiptypenote { get; set; }
        public Nullable<int> Companyid { get; set; }
        public Nullable<int> officestate { get; set; }
        public string BranchName { get; set; }
        public string staffid { get; set; }
        public Nullable<int> Subscriptionplanid { get; set; }
        public Nullable<bool> Hasdependents { get; set; }
        public string Specialidcardfield1 { get; set; }
        public string Specialidcardfield2 { get; set; }
        public string Specialidcardfield3 { get; set; }
        public Nullable<int> Staffprofileid { get; set; }
        public Nullable<bool> IdCardPrinted { get; set; }
        public string Primaryprovider { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Hasactivesubscription { get; set; }
        public Nullable<bool> Isexpundged { get; set; }
        public string ExpungeNote { get; set; }
        public Nullable<int> Expungedby { get; set; }
        public Nullable<System.DateTime> Dateexpunged { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Datereceived { get; set; }
        public string BranchID { get; set; }
        public string s_Surname { get; set; }
        public string s_Othernames { get; set; }
        public Nullable<System.DateTime> s_Dob { get; set; }
        public Nullable<int> S_Sex { get; set; }
        public string S_mobile { get; set; }
        public string S_email { get; set; }
        public string S_hospital { get; set; }
        public string S_medicalhistory { get; set; }
        public string child1_Surname { get; set; }
        public string child1_Othernames { get; set; }
        public Nullable<System.DateTime> child1_Dob { get; set; }
        public Nullable<int> child1_Sex { get; set; }
        public string child1_mobile { get; set; }
        public string child1_email { get; set; }
        public string child1_hospital { get; set; }
        public string child1_medicalhistory { get; set; }
        public string child2_Surname { get; set; }
        public string child2_Othernames { get; set; }
        public Nullable<System.DateTime> child2_Dob { get; set; }
        public Nullable<int> child2_Sex { get; set; }
        public string child2_mobile { get; set; }
        public string child2_email { get; set; }
        public string child2_hospital { get; set; }
        public string child2_medicalhistory { get; set; }
        public string child3_Surname { get; set; }
        public string child3_Othernames { get; set; }
        public Nullable<System.DateTime> child3_Dob { get; set; }
        public Nullable<int> child3_Sex { get; set; }
        public string child3_mobile { get; set; }
        public string child3_email { get; set; }
        public string child3_hospital { get; set; }
        public string child3_medicalhistory { get; set; }
        public string child4_Surname { get; set; }
        public string child4_Othernames { get; set; }
        public Nullable<System.DateTime> child4_Dob { get; set; }
        public Nullable<int> child4_Sex { get; set; }
        public string child4_mobile { get; set; }
        public string child4_email { get; set; }
        public string child4_hospital { get; set; }
        public string child4_medicalhistory { get; set; }
        public Nullable<bool> addspouse { get; set; }
        public Nullable<bool> addchild1 { get; set; }
        public Nullable<bool> addchild2 { get; set; }
        public Nullable<bool> addchild3 { get; set; }
        public Nullable<bool> addchild4 { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> EnrolleePassportId { get; set; }
        public Nullable<int> SiteId { get; set; }
    }
}
