//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffUploadJob
    {
        public int Id { get; set; }
        public string filelink { get; set; }
        public string JobStatus { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> Subsidiary { get; set; }
        public string ExpungeMode { get; set; }
        public Nullable<int> TotalRecord { get; set; }
        public Nullable<int> TotalRecordDone { get; set; }
        public Nullable<int> TotalRecordSuccess { get; set; }
        public Nullable<int> TotalRecordFailed { get; set; }
        public Nullable<int> TotalStaffForExpunged { get; set; }
        public Nullable<int> TotalStaffAdded { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string errorlist { get; set; }
        public string Analysislink { get; set; }
        public Nullable<bool> approved { get; set; }
        public Nullable<System.DateTime> dateapproved { get; set; }
        public Nullable<int> approvedby { get; set; }
    }
}
