//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Old_20180702
    {
        public int Id { get; set; }
        public string CompanyId { get; set; }
        public Nullable<int> CompanySubsidiary { get; set; }
        public string StaffFullname { get; set; }
        public Nullable<int> StaffPlanid { get; set; }
        public Nullable<bool> HasProfile { get; set; }
        public Nullable<int> Profileid { get; set; }
        public Nullable<int> Createdby { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<bool> IsExpunged { get; set; }
        public string StaffId { get; set; }
        public Nullable<int> NewStaffId { get; set; }
        public Nullable<System.DateTime> stafflinkDate { get; set; }
        public Nullable<int> stafflinkUSer { get; set; }
        public Nullable<int> StaffJobId { get; set; }
    }
}
