//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCMultiEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<long> Zone { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> EnrolleeDetailsPageId { get; set; }
        public Nullable<int> EnrolleeListPageId { get; set; }
        public Nullable<int> EnrolleePageId { get; set; }
        public Nullable<int> ProviderPageId { get; set; }
        public Nullable<int> EnrolleeRegPageId { get; set; }
        public Nullable<int> DelistedProviderPageId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Document Document1 { get; set; }
        public virtual Document Document2 { get; set; }
        public virtual Document Document3 { get; set; }
        public virtual Document Document4 { get; set; }
        public virtual Document Document5 { get; set; }
    }
}
